#include "spmv.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <limits>
#include <random>
namespace hccl_spmv {
bool CSRMatrix::validate(std::string* e) const { if(rows<0||cols<0||row_ptr.size()!=static_cast<size_t>(rows+1)||row_ptr.empty()||row_ptr.front()!=0||row_ptr.back()!=static_cast<int32_t>(values.size())||values.size()!=col_idx.size()){if(e)*e="invalid CSR dimensions";return false;} for(size_t i=1;i<row_ptr.size();++i) if(row_ptr[i]<row_ptr[i-1]){if(e)*e="row_ptr is not monotonic";return false;} for(auto c:col_idx) if(c<0||c>=cols){if(e)*e="column index out of range";return false;} return true; }
bool CSRMatrix::save(const std::string& p,std::string* e) const { std::ofstream f(p,std::ios::binary); if(!f){if(e)*e="cannot open "+p;return false;} f.write("CSR1",4); int64_t n=nnz(); f.write(reinterpret_cast<const char*>(&rows),4);f.write(reinterpret_cast<const char*>(&cols),4);f.write(reinterpret_cast<const char*>(&n),8); f.write(reinterpret_cast<const char*>(row_ptr.data()),row_ptr.size()*4);f.write(reinterpret_cast<const char*>(col_idx.data()),col_idx.size()*4);f.write(reinterpret_cast<const char*>(values.data()),values.size()*4); return !!f; }
bool CSRMatrix::load(const std::string& p,CSRMatrix* m,std::string* e){if(!m){return false;}std::ifstream f(p,std::ios::binary);char magic[4];int64_t n=0;if(!f.read(magic,4)||std::string(magic,4)!="CSR1"||!f.read(reinterpret_cast<char*>(&m->rows),4)||!f.read(reinterpret_cast<char*>(&m->cols),4)||!f.read(reinterpret_cast<char*>(&n),8)||n<0){if(e)*e="invalid CSR cache "+p;return false;}m->row_ptr.resize(static_cast<size_t>(m->rows)+1);m->col_idx.resize(static_cast<size_t>(n));m->values.resize(static_cast<size_t>(n));f.read(reinterpret_cast<char*>(m->row_ptr.data()),m->row_ptr.size()*4);f.read(reinterpret_cast<char*>(m->col_idx.data()),m->col_idx.size()*4);f.read(reinterpret_cast<char*>(m->values.data()),m->values.size()*4);return f&&m->validate(e);}
static std::pair<int,int> shape(const std::string& n){if(n=="U1"||n=="L1"||n=="B1")return {100000,100000};return {1000000,1000000};}
CSRMatrix generate_matrix(const std::string& name){auto [rows,cols]=shape(name);int64_t target=(rows==100000?1000000:10000000);CSRMatrix m;m.rows=rows;m.cols=cols;m.row_ptr.resize(static_cast<size_t>(rows)+1);std::mt19937 rng(42);std::uniform_real_distribution<float> val(name[0]=='L'?0.25f:0.5f,name[0]=='B'?1.0f:1.5f);int base=static_cast<int>(target/rows),rem=static_cast<int>(target%rows);for(int r=0;r<rows;++r)m.row_ptr[r+1]=m.row_ptr[r]+base+(r<rem);m.col_idx.resize(target);m.values.resize(target);std::uniform_int_distribution<int> col(0,cols-1);for(int r=0;r<rows;++r){int b=m.row_ptr[r],e=m.row_ptr[r+1];for(int p=b;p<e;++p){m.col_idx[p]=static_cast<int32_t>((static_cast<uint64_t>(r)*1315423911u+p*2654435761u)%static_cast<uint64_t>(cols));m.values[p]=val(rng);}}return m;}
std::vector<float> generate_x(int32_t cols){std::mt19937 rng(42);std::uniform_real_distribution<float>d(0,1);std::vector<float>x(cols);for(auto&v:x)v=d(rng);return x;}
void spmv_cpu(const CSRMatrix&m,const std::vector<float>&x,std::vector<float>*y,int32_t first,int32_t last){if(last<0||last>m.rows)last=m.rows;if(first<0)first=0;if(y->size()!=static_cast<size_t>(m.rows))y->assign(m.rows,0);for(int r=first;r<last;++r){float s=0;for(int p=m.row_ptr[r];p<m.row_ptr[r+1];++p)s+=m.values[p]*x[m.col_idx[p]];(*y)[r]=s;}}
double max_relative_error(const std::vector<float>&a,const std::vector<float>&b){if(a.size()!=b.size())return std::numeric_limits<double>::infinity();double e=0;for(size_t i=0;i<a.size();++i)e=std::max(e,std::abs(double(a[i])-b[i])/std::max(std::abs(double(a[i])),1e-12));return e;}
}
