#ifndef TILING_KEY_${OPERATOR_NAME}_H
#define TILING_KEY_${OPERATOR_NAME}_H
#include "ascendc/host_api/tiling/template_argument.h"

// Tiling 模板参数定义
ASCENDC_TPL_ARGS_DECL(${OPERATOR_CLASS},  // 算子名
// DataType 类型的模板参数定义
ASCENDC_TPL_DATATYPE_DECL(D_T_X, C_DT_FLOAT, C_DT_FLOAT16, ASCENDC_TPL_INPUT(0)),  // 输入 x 的数据类型
ASCENDC_TPL_DATATYPE_DECL(D_T_Y, C_DT_FLOAT, C_DT_FLOAT16, ASCENDC_TPL_INPUT(1)),  // 输入 y 的数据类型
ASCENDC_TPL_DATATYPE_DECL(D_T_Z, C_DT_FLOAT, C_DT_FLOAT16, ASCENDC_TPL_OUTPUT(0)), // 输出 z 的数据类型
// 自定义 UINT 类型的模板参数定义
ASCENDC_TPL_UINT_DECL(TILE_NUM, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_MIX, 2, 0, 2, 3, 5, 10),
// 自定义 bool 类型的模板参数定义
ASCENDC_TPL_BOOL_DECL(IS_SPLIT, 0, 1),
);

// 定义合法的参数组合
ASCENDC_TPL_SEL(
    // 组合1: float32 类型
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT),
        ASCENDC_TPL_DATATYPE_SEL(D_T_Y, C_DT_FLOAT),
        ASCENDC_TPL_DATATYPE_SEL(D_T_Z, C_DT_FLOAT),
    ),
    // 组合2: float16 类型
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DATATYPE_SEL(D_T_X, C_DT_FLOAT16),
        ASCENDC_TPL_DATATYPE_SEL(D_T_Y, C_DT_FLOAT16),
        ASCENDC_TPL_DATATYPE_SEL(D_T_Z, C_DT_FLOAT16),
    ),
);

#endif  // TILING_KEY_${OPERATOR_NAME}_H
